// Generated by `wit-bindgen` 0.8.0. DO NOT EDIT!
#include "assemblylift.h"


typedef struct {
  bool is_err;
  union {
    akkoro_assemblylift_asml_io_ioid_t ok;
    akkoro_assemblylift_asml_io_io_error_t err;
  } val;
} assemblylift_result_ioid_io_error_t;

typedef struct {
  bool is_err;
  union {
    assemblylift_list_u8_t ok;
    akkoro_assemblylift_asml_io_poll_error_t err;
  } val;
} assemblylift_result_list_u8_poll_error_t;

__attribute__((__import_module__("akkoro:assemblylift/asml-io"), __import_name__("invoke")))
void __wasm_import_akkoro_assemblylift_asml_io_invoke(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("akkoro:assemblylift/asml-io"), __import_name__("poll")))
void __wasm_import_akkoro_assemblylift_asml_io_poll(int32_t, int32_t);

__attribute__((__import_module__("akkoro:assemblylift/asml-rt"), __import_name__("success")))
void __wasm_import_akkoro_assemblylift_asml_rt_success(int32_t, int32_t);

__attribute__((__import_module__("akkoro:assemblylift/asml-rt"), __import_name__("failure")))
void __wasm_import_akkoro_assemblylift_asml_rt_failure(int32_t, int32_t);

__attribute__((__import_module__("akkoro:assemblylift/asml-rt"), __import_name__("log")))
void __wasm_import_akkoro_assemblylift_asml_rt_log(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("akkoro:assemblylift/asml-rt"), __import_name__("get-input")))
void __wasm_import_akkoro_assemblylift_asml_rt_get_input(int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void akkoro_assemblylift_asml_rt_bytes_free(akkoro_assemblylift_asml_rt_bytes_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void assemblylift_list_u8_free(assemblylift_list_u8_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void assemblylift_string_set(assemblylift_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void assemblylift_string_dup(assemblylift_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void assemblylift_string_free(assemblylift_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool akkoro_assemblylift_asml_io_invoke(assemblylift_string_t *path, assemblylift_string_t *input, akkoro_assemblylift_asml_io_ioid_t *ret, akkoro_assemblylift_asml_io_io_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_assemblylift_asml_io_invoke((int32_t) (*path).ptr, (int32_t) (*path).len, (int32_t) (*input).ptr, (int32_t) (*input).len, ptr);
  assemblylift_result_ioid_io_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool akkoro_assemblylift_asml_io_poll(akkoro_assemblylift_asml_io_ioid_t ioid, assemblylift_list_u8_t *ret, akkoro_assemblylift_asml_io_poll_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_assemblylift_asml_io_poll((int32_t) (ioid), ptr);
  assemblylift_result_list_u8_poll_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (assemblylift_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

void akkoro_assemblylift_asml_rt_success(akkoro_assemblylift_asml_rt_bytes_t *response) {
  __wasm_import_akkoro_assemblylift_asml_rt_success((int32_t) (*response).ptr, (int32_t) (*response).len);
}

void akkoro_assemblylift_asml_rt_failure(akkoro_assemblylift_asml_rt_bytes_t *response) {
  __wasm_import_akkoro_assemblylift_asml_rt_failure((int32_t) (*response).ptr, (int32_t) (*response).len);
}

void akkoro_assemblylift_asml_rt_log(akkoro_assemblylift_asml_rt_log_level_t level, assemblylift_string_t *context, assemblylift_string_t *message) {
  __wasm_import_akkoro_assemblylift_asml_rt_log((int32_t) level, (int32_t) (*context).ptr, (int32_t) (*context).len, (int32_t) (*message).ptr, (int32_t) (*message).len);
}

void akkoro_assemblylift_asml_rt_get_input(assemblylift_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_assemblylift_asml_rt_get_input(ptr);
  *ret = (assemblylift_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

extern void __component_type_object_force_link_assemblylift(void);
void __component_type_object_force_link_assemblylift_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_assemblylift();
}
