// Generated by `wit-bindgen` 0.8.0. DO NOT EDIT!
#include "jwt.h"


typedef struct {
  bool is_err;
  union {
    akkoro_jwt_decoder_verify_result_t ok;
    akkoro_jwt_decoder_jwt_error_t err;
  } val;
} jwt_result_verify_result_jwt_error_t;

__attribute__((__import_module__("akkoro:jwt/decoder"), __import_name__("decode-verify")))
void __wasm_import_akkoro_jwt_decoder_decode_verify(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void akkoro_jwt_decoder_validation_params_free(akkoro_jwt_decoder_validation_params_t *ptr) {
  jwt_string_free(&ptr->iss);
  jwt_string_free(&ptr->aud);
}

void jwt_string_set(jwt_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void jwt_string_dup(jwt_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void jwt_string_free(jwt_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool akkoro_jwt_decoder_decode_verify(jwt_string_t *token, jwt_string_t *jwks, akkoro_jwt_decoder_validation_params_t *params, akkoro_jwt_decoder_verify_result_t *ret, akkoro_jwt_decoder_jwt_error_t *err) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_jwt_decoder_decode_verify((int32_t) (*token).ptr, (int32_t) (*token).len, (int32_t) (*jwks).ptr, (int32_t) (*jwks).len, (int32_t) ((*params).iss).ptr, (int32_t) ((*params).iss).len, (int32_t) ((*params).aud).ptr, (int32_t) ((*params).aud).len, ptr);
  jwt_result_verify_result_jwt_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (akkoro_jwt_decoder_verify_result_t) {
        (int32_t) (*((uint8_t*) (ptr + 1))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

extern void __component_type_object_force_link_jwt(void);
void __component_type_object_force_link_jwt_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_jwt();
}
