// Generated by `wit-bindgen` 0.8.0. DO NOT EDIT!
#include "opa.h"


typedef struct {
  bool is_err;
  union {
    akkoro_opa_module_policy_t ok;
    akkoro_opa_module_policy_error_t err;
  } val;
} opa_result_policy_policy_error_t;

__attribute__((__import_module__("akkoro:opa/module"), __import_name__("new-policy")))
void __wasm_import_akkoro_opa_module_new_policy(int32_t, int32_t, int32_t);

__attribute__((__import_module__("akkoro:opa/module"), __import_name__("eval")))
void __wasm_import_akkoro_opa_module_eval(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void opa_list_string_free(opa_list_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    opa_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void akkoro_opa_module_policy_free(akkoro_opa_module_policy_t *ptr) {
  opa_string_free(&ptr->id);
  opa_list_string_free(&ptr->entrypoints);
}

void opa_list_u8_free(opa_list_u8_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void opa_string_set(opa_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void opa_string_dup(opa_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void opa_string_free(opa_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool akkoro_opa_module_new_policy(opa_list_u8_t *bytes, akkoro_opa_module_policy_t *ret, akkoro_opa_module_policy_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[20];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_opa_module_new_policy((int32_t) (*bytes).ptr, (int32_t) (*bytes).len, ptr);
  opa_result_policy_policy_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (akkoro_opa_module_policy_t) {
        (opa_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        (opa_list_string_t) { (opa_string_t*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) },
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

void akkoro_opa_module_eval(opa_string_t *id, opa_string_t *data, opa_string_t *input, opa_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_opa_module_eval((int32_t) (*id).ptr, (int32_t) (*id).len, (int32_t) (*data).ptr, (int32_t) (*data).len, (int32_t) (*input).ptr, (int32_t) (*input).len, ptr);
  *ret = (opa_string_t) { (char*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

extern void __component_type_object_force_link_opa(void);
void __component_type_object_force_link_opa_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_opa();
}
