// Generated by `wit-bindgen` 0.8.0. DO NOT EDIT!
#include "secrets.h"


typedef struct {
  bool is_err;
  union {
    akkoro_secrets_secret_storage_secret_t ok;
    akkoro_secrets_secret_storage_error_t err;
  } val;
} secrets_result_secret_error_t;

__attribute__((__import_module__("akkoro:secrets/secret-storage"), __import_name__("get-secret-value")))
void __wasm_import_akkoro_secrets_secret_storage_get_secret_value(int32_t, int32_t, int32_t);

__attribute__((__import_module__("akkoro:secrets/secret-storage"), __import_name__("set-secret-value")))
void __wasm_import_akkoro_secrets_secret_storage_set_secret_value(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void secrets_list_u8_free(secrets_list_u8_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void secrets_option_list_u8_free(secrets_option_list_u8_t *ptr) {
  if (ptr->is_some) {
    secrets_list_u8_free(&ptr->val);
  }
}

void akkoro_secrets_secret_storage_secret_free(akkoro_secrets_secret_storage_secret_t *ptr) {
  secrets_string_free(&ptr->id);
  secrets_option_list_u8_free(&ptr->value);
}

void akkoro_secrets_secret_storage_key_free(akkoro_secrets_secret_storage_key_t *ptr) {
  secrets_string_free(ptr);
}

void secrets_string_set(secrets_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void secrets_string_dup(secrets_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void secrets_string_free(secrets_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool akkoro_secrets_secret_storage_get_secret_value(secrets_string_t *id, akkoro_secrets_secret_storage_secret_t *ret, akkoro_secrets_secret_storage_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_secrets_secret_storage_get_secret_value((int32_t) (*id).ptr, (int32_t) (*id).len, ptr);
  secrets_result_secret_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      secrets_option_list_u8_t option;
      switch ((int32_t) (*((uint8_t*) (ptr + 12)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (secrets_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 16))), (size_t)(*((int32_t*) (ptr + 20))) };
          break;
        }
      }
      
      result.val.ok = (akkoro_secrets_secret_storage_secret_t) {
        (secrets_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        option,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool akkoro_secrets_secret_storage_set_secret_value(secrets_string_t *id, secrets_list_u8_t *value, akkoro_secrets_secret_storage_key_t *key, akkoro_secrets_secret_storage_secret_t *ret, akkoro_secrets_secret_storage_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_akkoro_secrets_secret_storage_set_secret_value((int32_t) (*id).ptr, (int32_t) (*id).len, (int32_t) (*value).ptr, (int32_t) (*value).len, (int32_t) (*key).ptr, (int32_t) (*key).len, ptr);
  secrets_result_secret_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      secrets_option_list_u8_t option;
      switch ((int32_t) (*((uint8_t*) (ptr + 12)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (secrets_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 16))), (size_t)(*((int32_t*) (ptr + 20))) };
          break;
        }
      }
      
      result.val.ok = (akkoro_secrets_secret_storage_secret_t) {
        (secrets_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        option,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

extern void __component_type_object_force_link_secrets(void);
void __component_type_object_force_link_secrets_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_secrets();
}
